#!/bin/sh -e
#
# /etc/init.d/webcam: Start the webcam
#
### BEGIN INIT INFO
# Provides:       webcam
# Required-Start: $local_fs $syslog $remote_fs
# Required-Stop: $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start webcam
# Description: loads webcam
### END INIT INFO

# source function library
. /lib/lsb/init-functions
. /etc/profile

RETVAL=0
prog=webcam

start() {
	echo -n "Starting $prog:"
        /root/webcam.sh 2>&1 1> /var/log/webcam.log &
        echo -n "...done"
	RETVAL=$?
	echo
}

stop() {
	echo -n "Stopping $prog:"
        ps ax | grep avconv | grep -v grep && killall avconv
        echo -n "...done"
	RETVAL=$?
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	reload)
		reload
		;;
	condrestart)
		if [ -f /var/lock/subsys/$prog ] ; then
			stop
			# avoid race
			sleep 3
			start
		fi
		;;
	status)
		status $prog
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|condrestart|status}"
		RETVAL=1
esac
exit $RETVAL

